### ISSUE TITLE
请问模板如何禁用TLS1.0 TLS1.1

### ISSUE THREAD

**Issue by xhqpp** [v2fly/v2ray-examples#14]
我用的是VLESS-TCP-TLS (minimal by rprx)这个模板
默认开启TLS1.0 TLS1.1导致
在Qualys SSL Labs's SSL Server Test测试的成绩是B
请问如何禁用TLS1.0 TLS1.1

**Comment by rprx** [comment]
目前 v2ray 无法自定义加密套件，请等待更新。
