### ISSUE TITLE
关于fallbacks的疑问，希望解答一下

### ISSUE THREAD

**Issue by usgate** [v2fly/v2ray-examples#16]
我阅读了v2fly.org,vless协议下关于fallback的解释，感觉还不是太明白，相信还有很多和我一样的人。希望在官网文档解释下fallback是什么，为什么设计fallback，以及怎么配置fallback。
例如：配置文件：https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS-WS%20(recommended)/config_server.json 中

  "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
fallback数组中有两个对象，什么时候调用第一个，什么时候调用第二个，或者说第一个和第二个怎么联系的。

**Comment by rprx** [comment]
> 希望在官网文档解释下fallback是什么，为什么设计fallback，以及怎么配置fallback。

这两天会写一下。

**Comment by ixxmu** [comment]
回落到不同端口的配置，是否可以在client客户端直接使用回落端口连接，比如回落至ws 1234，客户端使用ws 1234 端口是否可以直连？或者有什么验证阻断客户端对回落的端口进行隐藏？ 谢谢

**Comment by rprx** [comment]
> 
> 
> 回落到不同端口的配置，是否可以在client客户端直接使用回落端口连接，比如回落至ws 1234，客户端使用ws 1234 端口是否可以直连？或者有什么验证阻断客户端对回落的端口进行隐藏？ 谢谢

不可以直连，因为 listen 127.0.0.1，以及往往有防火墙（请补一下基础）。

**Comment by ixxmu** [comment]
> > 回落到不同端口的配置，是否可以在client客户端直接使用回落端口连接，比如回落至ws 1234，客户端使用ws 1234 端口是否可以直连？或者有什么验证阻断客户端对回落的端口进行隐藏？ 谢谢
> 
> 不可以直连，因为 listen 127.0.0.1，以及往往有防火墙（请补一下基础）。

对哦，listen可以控制，谢谢！

**Comment by canwushuang** [comment]
vless协议只走tcp，直连ip。没有tls解密，那么fallback怎么填写? 看手册fallback必填的。

**Comment by GleenJi** [comment]
v2fly官方文档的FallbackObject有一句话：“通常，你需要先设置一组 alpn 和 path 均省略或为空的默认回落，然后再按需配置其它分流。”所以多出一个元素
{
"dest": 80
},
这个是默认的，而这个
{
"path": "/websocket", // 必须换成自定义的 PATH
"dest": 1234,
"xver": 1
}
元素的配置才是需要的

**Comment by imess** [comment]
可以理解成v做前置，担任流量分发（回落）的角色（常规的话是web服务器在前，v在后端，现在刚好对换，相当于直连），类似trojan/HAproxy那样的角色。

**Comment by tefiszx** [comment]
fallback dest 80是否意味着不需要在caddy这种http server中配置reverse_proxy这样的配置，只要搭建好http server就可以了。

**Comment by ixxmu** [comment]
示例配置 _VLESS+TCP_ 是否支持 fallback 到 WebSocket，还是只有_VLESS+**TLS**+TCP_的组合才支持 fallback 到 WebSocket 的？ v2ray只充当内网服务不向外暴露端口

**Comment by rprx** [comment]
> 
> 
> 示例配置 _VLESS+TCP_ 是否支持 fallback 到 WebSocket，还是只有_VLESS+**TLS**+TCP_的组合才支持 fallback 到 WebSocket 的？ v2ray只充当内网服务不向外暴露端口

可以前置其它程序处理 TLS，但 VLESS 拿不到 ALPN 了。

**Comment by GleenJi** [comment]
有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢

**Comment by imess** [comment]
> 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢

个人理解，主要是提供一个精简的通用接口吧，由vless接管流量进行分发，兼顾性能,隐蔽性和后续可扩展性，不用受制于前置web服务器，同时也不会影响正常的web服务

**Comment by smallprogram** [comment]
> 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢

fallback用于非代理流量分流，主要目的有反侦测，建站等。

以前VMESS使用前置Web服务器(Nginx,Caddy等)作为反向代理，当符合代理特征流量请求通过web服务器转发至v2ray进行科学上网，而非代理流量的请求转发至网站，返回一个网站。这种TLS+VMESS+WS等模式虽然相对安全也能满足建站需求，但是会让科学上网效率降低。网速变慢。

现在VLESS就不一样，证书私钥都配置在v2ray中，当作前置代理，当符合代理特征流量请求进入时直接走v2ray。不符合特征的流量请求会通过fallback转发至其他Web服务器(Nginx,Caddy等)。这种模式既保证了速度、安全性，又可以同时满足建站需求。

粗略的一讲。有讲的不对的地方海涵。顺带一提4.29.0的XTLS真香。

**Comment by imess** [comment]
> > 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> > 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢
> 
> fallback用于非代理流量分流，主要目的有反侦测，建站等。
> 
> 以前VMESS使用前置Web服务器(Nginx,Caddy等)作为反向代理，当符合代理特征流量请求通过web服务器转发至v2ray进行科学上网，而非代理流量的请求转发至网站，返回一个网站。这种TLS+VMESS+WS等模式虽然相对安全也能满足建站需求，但是会让科学上网效率降低。网速变慢。
> 
> 现在VLESS就不一样，证书私钥都配置在v2ray中，当作前置代理，当符合代理特征流量请求进入时直接走v2ray。不符合特征的流量请求会通过fallback转发至其他Web服务器(Nginx,Caddy等)。这种模式既保证了速度、安全性，又可以同时满足建站需求。
> 
> 粗略的一讲。有讲的不对的地方海涵。顺带一提4.29.0的XTLS真香。

确实香，少了内层tls开销，吞吐量一下子上去了，稳定性也好了，但由于牺牲了mux，网页打开速度明显慢了不少，可谓有得必有失了

**Comment by GleenJi** [comment]
> 
> 
> > 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> > 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢
> 
> fallback用于非代理流量分流，主要目的有反侦测，建站等。
> 
> 以前VMESS使用前置Web服务器(Nginx,Caddy等)作为反向代理，当符合代理特征流量请求通过web服务器转发至v2ray进行科学上网，而非代理流量的请求转发至网站，返回一个网站。这种TLS+VMESS+WS等模式虽然相对安全也能满足建站需求，但是会让科学上网效率降低。网速变慢。
> 
> 现在VLESS就不一样，证书私钥都配置在v2ray中，当作前置代理，当符合代理特征流量请求进入时直接走v2ray。不符合特征的流量请求会通过fallback转发至其他Web服务器(Nginx,Caddy等)。这种模式既保证了速度、安全性，又可以同时满足建站需求。
> 
> 粗略的一讲。有讲的不对的地方海涵。顺带一提4.29.0的XTLS真香。

感谢解答，就是说以前是web服务（nginx/caddy）在前，占用443/80端口，接收客户端送来的流量，由web服务进行对流量的分发，是v2ray流量转而进入v2ray，是网站web服务就返回网站；

现在是v2ray在前占用443端口，是v2ray流量直接走v2ray，不是v2ray流量 v2ray就把网站流量通过fallback转到web服务监听的端口？那nginx/caddy就不能占用443了吧？

还有，使用fallback貌似就不能用websocket了，想用cf的cdn好像只能用websocket？因为我的VPS很普通，基本都是用cdn来提速的，直连科学上网反而速度不行严重丢包。

**Comment by rprx** [comment]
我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。

https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER

**Comment by GleenJi** [comment]
> 
> 
> > 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> > 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢
> 
> 个人理解，主要是提供一个精简的通用接口吧，由vless接管流量进行分发，兼顾性能,隐蔽性和后续可扩展性，不用受制于前置web服务器，同时也不会影响正常的web服务

感谢解答，意思就是以前web服务在前分发流量，现在是v2ray在前分发流量；
不过只是单纯科学上网的话，既然能直接连接到VPS，那感觉应该也就没必要用fallback再搞分流
还有是不是用了fallback没法用cdn了

**Comment by imess** [comment]
> > > 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> > > 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢
> > 
> > 
> > 个人理解，主要是提供一个精简的通用接口吧，由vless接管流量进行分发，兼顾性能,隐蔽性和后续可扩展性，不用受制于前置web服务器，同时也不会影响正常的web服务
> 
> 感谢解答，意思就是以前web服务在前分发流量，现在是v2ray在前分发流量；
> 不过只是单纯科学上网的话，既然能直接连接到VPS，那感觉应该也就没必要用fallback再搞分流
> 还有是不是用了fallback没法用cdn了

如果你不用xtls，不追求极致fq性能，又想尝试vless的话，完全不需要大改原来的配置，比如原来cdn -> web server -> vmess+ws，只是简单的把vmess改成vless，alterId去掉，security改成encryption:none，服务端fallback到ws inbound，便可换取一定的性能提升，拓补依然不变。

如果要用到xtls，那就要牺牲cdn，ws和mux了，v2ray必须前置，web server在后（web server非要在前的话必须支持sni分流）。

vless只是锦上添花的功能，建议看一遍所有的示例配置，结合作者的回答以及根据实际需求配置。vless+xtls下面的帖子有讨论
https://github.com/v2ray/v2ray-core/issues/2636

这是这段时间折腾下来的一点肤浅经验，如果有错请大佬们指正。

**Comment by GleenJi** [comment]
> 
> 
> > > > 有大佬可以解释一下fallback有啥用嘛，，如过只是单纯的科学上网，既然都能直接连接VPS了，还用fallback分流干啥？就比如说，普通情况下一般用vmess/vless+tcp/ws+tls即可，因为VPS的ip可以连的上，如果被封，再套cdn即vmess/vless+ws+tls+cdn。
> > > > 那么这个fallback有啥用？小白不懂希望有大佬可简单讲一下,谢谢
> > > 
> > > 
> > > 个人理解，主要是提供一个精简的通用接口吧，由vless接管流量进行分发，兼顾性能,隐蔽性和后续可扩展性，不用受制于前置web服务器，同时也不会影响正常的web服务
> > 
> > 
> > 感谢解答，意思就是以前web服务在前分发流量，现在是v2ray在前分发流量；
> > 不过只是单纯科学上网的话，既然能直接连接到VPS，那感觉应该也就没必要用fallback再搞分流
> > 还有是不是用了fallback没法用cdn了
> 
> 如果你不用xtls，不追求极致fq性能，又想尝试vless的话，完全不需要大改原来的配置，比如原来cdn -> web server -> vmess+ws，只是简单的把vmess改成vless，alterId去掉，security改成encryption:none，服务端fallback到ws inbound，便可换取一定的性能提升，拓补依然不变。
> 
> 如果要用到xtls，那就要牺牲cdn，ws和mux了，v2ray必须前置，web server在后（web server非要在前的话必须支持sni分流）。
> 
> vless fallback只是锦上添花的功能，建议看一遍所有的示例配置，结合作者的回答以及根据实际需求配置。vless+xtls下面的帖子有讨论
> [v2ray/v2ray-core#2636](https://github.com/v2ray/v2ray-core/issues/2636)
> 
> 这是这段时间折腾下来的一点肤浅经验，如果有错请大佬们指正。

这是我服务端v2ray配置：
{
  "log": 
  {
    "loglevel": "warning",
    "access": "/v2raycaddy/log/v2ray/access.log",
    "error": "/v2raycaddy/log/v2ray/error.log"
  },

  "inbounds": 
  [
    {
      "port": 12346,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": 
      {
        "clients":
        [
          {
            "id": "my uuid"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": 
      {
        "network": "ws",
        "wsSettings": 
        {
          "path": "/example"
        }
      }
    }
  ],

  "outbounds":
  [
    {
      "protocol": "freedom",
      "settings": 
      {
        "domainStrategy": "UseIP"
      }
    }
  ],

  "dns":
  {
    "servers": 
    [
      "8.8.8.8",
      "1.1.1.1",
      "localhost"
    ]
  }
}
并且有web服务caddy监听443端口并自动申请证书，我没明白的是为什么需要用到你们说的fallback，我并没有用到fallback，这个配置模板和以前的caddy+vmess+ws+tls几乎一模样，就是单纯的把vmess改成了vless

**Comment by rprx** [comment]
> 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> 
> https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER

@GleenJi

**Comment by GleenJi** [comment]
> 
> 
> > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> 
> @GleenJi

经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址

**Comment by GleenJi** [comment]
> 
> 
> > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> 
> @GleenJi

这样确实就是v2ray在前，web服务在后，而不是以往的web服务在前，并代理v2ray流量再转向v2ray，这种效率肯定比v2ray在前web服务在后低，毕竟我们的目的是翻为主，网站为辅，感谢你们这些大佬的付出， 我这个小白又学到了更多东西

**Comment by rprx** [comment]
@GleenJi 

直连不需要 WS。

**Comment by GleenJi** [comment]
> @GleenJi
> 
> 直连不需要 WS。

主要是我必须要用cdn，我用的vps是最便宜的，性能不行，直连不如cdn，搭配cf自选ip即可让质量不好的vps发挥出性能，所以ws我必须得用，如果直连可以选择tcp+tls或者tcp+xtls，我一般不直连

**Comment by k79e** [comment]
既然是疑问那我就来了 fallback为啥配置后无效?
访问服务端还是原来一样报错404. 我开的ws模式+vless. fallback dest指向了一个web服务器

**Comment by GleenJi** [comment]
> 
> 
> 既然是疑问那我就来了 fallback为啥配置后无效?
> 访问服务端还是原来一样报错404. 我开的ws模式+vless. fallback dest指向了一个web服务器
> 还有例子里面的fallback连续写了好几个 如果fallback生效 他怎么划分的? 到底会走哪个?
> 
> 好吧我错了 说明书上写的 只可以用TCP+TLS 传输组合.

我就按配置例子来的，主配置是tcp+xtls，然后fallback到vless+ws

**Comment by missmuxixi** [comment]
> > 既然是疑问那我就来了 fallback为啥配置后无效?
> > 访问服务端还是原来一样报错404. 我开的ws模式+vless. fallback dest指向了一个web服务器
> > 还有例子里面的fallback连续写了好几个 如果fallback生效 他怎么划分的? 到底会走哪个?
> > 好吧我错了 说明书上写的 只可以用TCP+TLS 传输组合.
> 
> 我就按配置例子来的，主配置是tcp+xtls，然后fallback到vless+ws

我现在也碰到这个问题，可怎么配置fallback vless+ws都连不上，vless+xtls倒是可以，但是没法cdn，可以po一份fallback的配置么？

**Comment by rilyuuj** [comment]
> > > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> > 
> > 
> > @GleenJi
> 
> 经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
> 也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址

你好，能否贴一下您的caddy的配置，本人也需要反代网站和自动续订证书的功能，之前caddy的时候只要加上tls和proxy参数就可以了，现在改成caddy2，json配置完全没头绪怎么弄了，谢谢您了！

**Comment by man2018** [comment]
回落是不是不支持回落到动态网站，我设置回到动态网站，网页css就乱了，是用lnmp环境搭建的worepress网站

**Comment by GleenJi** [comment]
> 
> 
> > > > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > > > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> > > 
> > > 
> > > @GleenJi
> > 
> > 
> > 经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
> > 也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址
> 
> @GleenJi
> 你好，能否贴一下您的caddy的配置，本人也需要反代网站和自动续订证书的功能，之前caddy的时候只要加上tls和proxy参数就可以了，现在改成caddy2，json配置完全没头绪怎么弄了，谢谢您了！
> 还有个问题就是为什么fallback不直接设置成8443？这样caddy就不用设置reverse_proxy了？是caddyv2有什么要求吗？

我用的是Caddyfile，说实话可能不如用json格式，因为Caddyfile对格式要求严格，莫名多个空格可能caddy就无法启动，但是我没用过json，不会json。。。
这是我Caddyfile配置：
{
  http_port 80
  https_port 8443
}
http://www.mydomian.com {
  log {
    output file /overgfw/caddy/log/caddy.log
  }
  redir https://www.mydomian.com:8443
}
https://www.mydomian.com {
  log {
    output file /overgfw/caddy/log/caddys.log
  }
  tls {
    dns cloudflare {env.CLOUDFLARE_API_TOKEN}
  }
  reverse_proxy https://v.qq.com {
    header_up Host {http.reverse_proxy.upstream.hostport}
  }
}
另外不直接fallback到8443貌似xray/v2ray的fallback只能fallback到http端口，https就不行，当然我也是小白，具体也不是很清楚

**Comment by gcphym** [comment]
> fallback只能fallback到http端口，https就不行

"fallback只能fallback到http端口，https就不行" 同问，等待大佬解答

**Comment by rilyuuj** [comment]
> > > > > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > > > > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> > > > 
> > > > 
> > > > @GleenJi
> > > 
> > > 
> > > 经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
> > > 也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址
> > 
> > 
> > @GleenJi
> > 你好，能否贴一下您的caddy的配置，本人也需要反代网站和自动续订证书的功能，之前caddy的时候只要加上tls和proxy参数就可以了，现在改成caddy2，json配置完全没头绪怎么弄了，谢谢您了！
> > 还有个问题就是为什么fallback不直接设置成8443？这样caddy就不用设置reverse_proxy了？是caddyv2有什么要求吗？
> 
> 我用的是Caddyfile，说实话可能不如用json格式，因为Caddyfile对格式要求严格，莫名多个空格可能caddy就无法启动，但是我没用过json，不会json。。。
> 这是我Caddyfile配置：
> {
> http_port 80
> https_port 8443
> }
> http://www.mydomian.com {
> log {
> output file /overgfw/caddy/log/caddy.log
> }
> redir https://www.mydomian.com:8443
> }
> https://www.mydomian.com {
> log {
> output file /overgfw/caddy/log/caddys.log
> }
> tls {
> dns cloudflare {env.CLOUDFLARE_API_TOKEN}
> }
> reverse_proxy https://v.qq.com {
> header_up Host {http.reverse_proxy.upstream.hostport}
> }
> }
> 另外不直接fallback到8443貌似xray/v2ray的fallback只能fallback到http端口，https就不行，当然我也是小白，具体也不是很清楚

时隔多少又重新摸出caddy来，请问下给出的配置文件中这个作用是什么？
```
{
http_port 80
https_port 8443
}
```
另外这一段的是强制重定向http80端口到的https8443端口吗？
```
http://www.mydomian.com {
 log {
 output file /overgfw/caddy/log/caddy.log
 }
 redir https://www.mydomian.com:8443
 }
```

**Comment by GleenJi** [comment]
> 
> 
> > > > > > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > > > > > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> > > > > 
> > > > > 
> > > > > @GleenJi
> > > > 
> > > > 
> > > > 经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
> > > > 也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址
> > > 
> > > 
> > > @GleenJi
> > > 你好，能否贴一下您的caddy的配置，本人也需要反代网站和自动续订证书的功能，之前caddy的时候只要加上tls和proxy参数就可以了，现在改成caddy2，json配置完全没头绪怎么弄了，谢谢您了！
> > > 还有个问题就是为什么fallback不直接设置成8443？这样caddy就不用设置reverse_proxy了？是caddyv2有什么要求吗？
> > 
> > 
> > 我用的是Caddyfile，说实话可能不如用json格式，因为Caddyfile对格式要求严格，莫名多个空格可能caddy就无法启动，但是我没用过json，不会json。。。
> > 这是我Caddyfile配置：
> > {
> > http_port 80
> > https_port 8443
> > }
> > http://www.mydomian.com {
> > log {
> > output file /overgfw/caddy/log/caddy.log
> > }
> > redir https://www.mydomian.com:8443
> > }
> > https://www.mydomian.com {
> > log {
> > output file /overgfw/caddy/log/caddys.log
> > }
> > tls {
> > dns cloudflare {env.CLOUDFLARE_API_TOKEN}
> > }
> > reverse_proxy https://v.qq.com {
> > header_up Host {http.reverse_proxy.upstream.hostport}
> > }
> > }
> > 另外不直接fallback到8443貌似xray/v2ray的fallback只能fallback到http端口，https就不行，当然我也是小白，具体也不是很清楚
> 
> @GleenJi 时隔多日，又重新摸出caddy来>_<，请问下给出的配置文件中这个作用是什么？
> 
> ```
> {
> http_port 80
> https_port 8443
> }
> ```
> 
> 另外这一段的是强制重定向http80端口到的https8443端口吗？
> 
> ```
> http://www.mydomian.com {
>  log {
>  output file /overgfw/caddy/log/caddy.log
>  }
>  redir https://www.mydomian.com:8443
>  }
> ```

更改caddy的默认端口，默认是80和443，另一个是重定向从http://www.mydomian.com到https://www.mydomian.com:8443

**Comment by rilyuuj** [comment]
> > > > > > > 我插一句，fallbacks 的回落是为了网站，分流则是为了 **共存**，即你可以同时用多种方式连上服务端，而不用上去改配置。
> > > > > > > https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
> > > > > > 
> > > > > > 
> > > > > > @GleenJi
> > > > > 
> > > > > 
> > > > > 经过摸索今天才明白什么意思，主要是v2ray占用443端口以后，caddy就得换端口，因为我想让caddy反代一个网页，还想用caddy自动申请证书的功能，同时我还想用cf cdn，折腾过来折腾过去才把caddy v2的如何修改监听端口整明白，还有cf cdn的http、https所支持的所有端口弄清了，现在再用fallback+xtls+ws这个终极配置，访问我的网页:443端口时可以fallback到80端口然后再跳转到:8443端口成功反代一个网页了。
> > > > > 也就是科学上网时:443端口vless+fallback+ws成功，浏览器直接看我的网站时:443->:80->:8443显示的是我让caddy反代的一个网址
> > > > 
> > > > 
> > > > @GleenJi
> > > > 你好，能否贴一下您的caddy的配置，本人也需要反代网站和自动续订证书的功能，之前caddy的时候只要加上tls和proxy参数就可以了，现在改成caddy2，json配置完全没头绪怎么弄了，谢谢您了！
> > > > 还有个问题就是为什么fallback不直接设置成8443？这样caddy就不用设置reverse_proxy了？是caddyv2有什么要求吗？
> > > 
> > > 
> > > 我用的是Caddyfile，说实话可能不如用json格式，因为Caddyfile对格式要求严格，莫名多个空格可能caddy就无法启动，但是我没用过json，不会json。。。
> > > 这是我Caddyfile配置：
> > > {
> > > http_port 80
> > > https_port 8443
> > > }
> > > http://www.mydomian.com {
> > > log {
> > > output file /overgfw/caddy/log/caddy.log
> > > }
> > > redir https://www.mydomian.com:8443
> > > }
> > > https://www.mydomian.com {
> > > log {
> > > output file /overgfw/caddy/log/caddys.log
> > > }
> > > tls {
> > > dns cloudflare {env.CLOUDFLARE_API_TOKEN}
> > > }
> > > reverse_proxy https://v.qq.com {
> > > header_up Host {http.reverse_proxy.upstream.hostport}
> > > }
> > > }
> > > 另外不直接fallback到8443貌似xray/v2ray的fallback只能fallback到http端口，https就不行，当然我也是小白，具体也不是很清楚
> > 
> > 
> > @GleenJi 时隔多日，又重新摸出caddy来>_<，请问下给出的配置文件中这个作用是什么？
> > ```
> > {
> > http_port 80
> > https_port 8443
> > }
> > ```
> > 
> > 
> > 另外这一段的是强制重定向http80端口到的https8443端口吗？
> > ```
> > http://www.mydomian.com {
> >  log {
> >  output file /overgfw/caddy/log/caddy.log
> >  }
> >  redir https://www.mydomian.com:8443
> >  }
> > ```
> 
> 更改caddy的默认端口，默认是80和443，另一个是重定向从[http://www.mydomian.com到https://www.mydomian.com:8443](http://www.mydomian.com%E5%88%B0https://www.mydomian.com:8443)

明白了，我试了好几次，下面的代码系统识别不了
```
{
http_port 80
https_port 8443
}
```
我估计得把caddy服务器版本升级一下了。。
总之，感谢！
