### ISSUE TITLE
tls websocket cdn  配置问题

### ISSUE THREAD

**Issue by sugarleon** [v2fly/v2ray-examples#17]
按模板配置后一直提示  配置文件照搬模板 只修改了path uuid 证书 域名  请问怎么解决 
2020/09/01 12:06:40 [Warning] [2922928673] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.yybhpb.ga/62e9faad/): 520 Origin Error > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by DuckSoft** [comment]
套了 CloudFlare 吗？你源站掉了。

![图片](https://user-images.githubusercontent.com/7822648/91794762-73a4b600-ec4e-11ea-9f0f-cea9f607eaf2.png)

**Comment by sugarleon** [comment]
> 套了 CloudFlare 吗？你源站掉了。
> 
> ![图片](https://user-images.githubusercontent.com/7822648/91794762-73a4b600-ec4e-11ea-9f0f-cea9f607eaf2.png)

2020/09/01 12:39:58 [Warning] [189771819] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.yybhpb.ga/abecdc59/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

cloudflare  ssl/tls设置改成灵活 之后网站能打开了 提示还是这个

**Comment by DuckSoft** [comment]
你 nginx 没配转发。

> > 套了 CloudFlare 吗？你源站掉了。
> > ![图片](https://user-images.githubusercontent.com/7822648/91794762-73a4b600-ec4e-11ea-9f0f-cea9f607eaf2.png)
> 
> 2020/09/01 12:39:58 [Warning] [189771819] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.yybhpb.ga/abecdc59/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> 
> cloudflare ssl/tls设置改成灵活 之后网站能打开了 提示还是这个

**Comment by sugarleon** [comment]
是我的证书有问题吗  太难搞了。

**Comment by sugarleon** [comment]
> 你 nginx 没配转发。
> 
> > > 套了 CloudFlare 吗？你源站掉了。
> > > ![图片](https://user-images.githubusercontent.com/7822648/91794762-73a4b600-ec4e-11ea-9f0f-cea9f607eaf2.png)
> > 
> > 
> > 2020/09/01 12:39:58 [Warning] [189771819] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.yybhpb.ga/abecdc59/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> > cloudflare ssl/tls设置改成灵活 之后网站能打开了 提示还是这个

请问要怎么配置  cloudflare ssl/tls选项设置为灵活后可以打开网站  按照模板的配置 nginx监听80端口 其他的都没有修改 怎么使用fallbacks 回落呢。

**Comment by sugarleon** [comment]
server config
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "****",
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/****/",
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "****",
                            "keyFile": "****"
                        }
                    ]
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "****",
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,
                    "path": "/****/"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

client config

{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 1080,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "****",
                        "port": 443,
                        "users": [
                            {
                                "id": "****",
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "****"
                },
                "wsSettings": {
                    "path": "/****/"
                }
            }
        }
    ]
}

**Comment by RouRouX** [comment]
> 你 nginx 没配转发。

这种配置还需要配置nginx转发吗？443端口被v2占用着呢啊，我也是报一样的错，用的
https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS-WS%20(recommended)/config_server.json

**Comment by sugarleon** [comment]
> > 你 nginx 没配转发。
> 
> 这种配置还需要配置nginx转发吗？443端口被v2占用着呢啊，我也是报一样的错，用的
> https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS-WS%20(recommended)/config_server.json

更新vless 1.5 解决

**Comment by pklpkl0pkl** [comment]
套CloudFlare的话，需要在CloudFlare-【SSL/TLS】，设置成【完全】or【完全（严格）】
