### ISSUE TITLE
VLESS-TCP-TLS-WS配置，tls正常，ws报错

### ISSUE THREAD

**Issue by RouRouX** [v2fly/v2ray-examples#18]
用的是推荐配置
https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS-WS%20(recommended)/config_server.json
配置好了以后tls正常，ws报错，下面是v2客户端的报错提示

2020/09/01 12:55:14 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/api):  > unexpected EOF] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by rprx** [comment]
这样看不出什么信息，发一下实际的配置文件

**Comment by RouRouX** [comment]
`
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "157bc35b-4918-437b-885f-89d289be1ecd", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/api", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/ssl/v2ray/fullchain.pem", // 换成你的证书，绝对路径
                            "keyFile": "/etc/ssl/v2ray/privkey.pem" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "157bc35b-4918-437b-885f-89d289be1ecd", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,
                    "path": "/api" // 必须换成自定义的 PATH，需要和上面的一致
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
`

**Comment by RouRouX** [comment]
感觉和 https://github.com/v2fly/v2ray-examples/issues/17 中提到的很像，怎么更新vless1.5？

**Comment by rprx** [comment]
fallbacks 是 VLESS PREVIEW 1.5 的配置项，升级 v2ray-core 到最新版 v4.27.4 即可（文档中写了要求 v4.27.2+）

**Comment by RouRouX** [comment]
更新vless 1.5 解决 关闭了 感谢大佬的解答！辛苦了！
