### ISSUE TITLE
关于VLESS over ws，with TLS + CDN安全性的疑问？

### ISSUE THREAD

**Issue by jinaviva** [v2fly/v2ray-examples#19]
因为VLESS协议不加密，如果采用VLESS over ws，with TLS + CDN方案，CDN厂商是否能够看到ws协议承载的原始未加密VLESS数据，从而轻而易举知道该上游服务器为V2RAY服务器？CDN厂商作为一个中间人，到底看到的是原始VLESS数据，还是TLS保护下的数据？小弟这点始终没想得很明白，望大佬帮忙解释下！

**Comment by DuckSoft** [comment]
VLESS over WS 情形下，理论上 CDN 是能解密你的流量的。不信任 CDN 厂商的话，不要用这种模式。

**Comment by rprx** [comment]
可以看到你的 UUID 及传输数据（不过基本上也是 TLS 了）。

如果你用 CDN 却不信任 CDN 厂商，应该使用加密的 VMess + WSS，可以配置 VLESS fallbacks path 分流到它。
