### ISSUE TITLE
关于vless协议负载均衡

### ISSUE THREAD

**Issue by qiumzh** [v2fly/v2ray-examples#20]
目前的vless协议如何配置负载均衡？

 // {
        //     "protocol": "vless",
        //     "settings": {
        //         "vnext": [
        //             {
        //                 "address": "domain",
        //                 "port": 443,
        //                 "users": [
        //                     {
        //                         "id": "6e01f4b4-22ba-cd12-6c16-3eb0b6cc3bee",
        //                         "level": 0,
        //                         "encryption": "none"
        //                     }
        //                 ]
        //             },
        //             {
        //                 "address": "domain",
        //                 "port": 443,
        //                 "users": [
        //                     {
        //                         "id": "fd3afd2f-474b-81b4-4727-169c90073589",
        //                         "level": 0,
        //                         "encryption": "none"
        //                     }
        //                 ]
        //             },
        //             {
        //                 "address": "domain",
        //                 "port": 443,
        //                 "users": [
        //                     {
        //                         "id": "5574f130-9446-4746-a426-d778369e9115",
        //                         "level": 0,
        //                         "encryption": "none"
        //                     }
        //                 ]
        //             }
        //         ]
        //     },
        //     "streamSettings": {
        //         "network": "tcp",
        //         "security": "tls"
        //     },
        //     "tag": "proxy-vless-out"
        // },

像这种好像是可以实现负载，但使用不了CDN。如果要使用CDN该如何配置才能实现负载均衡呢？

**Comment by rprx** [comment]
域名及 WebSocket 的 PATH 都写在单个 outbound 的 streamSettings 那里，如果不改代码，貌似无法实现这部分的负载均衡。

但是你可以给 vnext 的数个 address 填 CDN 的不同 IP，可以实现客户端的简单负载均衡（服务端则最终还是一个服务器）。

**Comment by rprx** [comment]
> 域名及 WebSocket 的 PATH 都写在单个 outbound 的 streamSettings 那里，如果不改代码，貌似无法实现这部分的负载均衡。

勘误：你可以使用路由的 balancers 实现这部分的负载均衡。

**Comment by qiumzh** [comment]
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 10800,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "example.com", // 换成你的域名或服务器 IP（发起请求时无需解析域名了）
                        "port": 443,
                        "users": [
                            {
                                "id": "", // 填写你的 UUID
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "example.com" // 换成你的域名
                },
                "wsSettings": {
                    "path": "/websocket" // 必须换成自定义的 PATH，需要和服务端的一致
                }
            }
        }
    ]
}
这里的tlsSettings已经限制了多个域名使用相当的配置。
路由的 balancers ，满足不了我的需求，我想把所有的科学上网流量轮询均匀的分发给每台服务器；
但是路由的balancers，只能把某些流量指定到某台服务器。

**Comment by rprx** [comment]
> 但是路由的balancers，只能把某些流量指定到某台服务器。

并不是，请看 https://www.v2fly.org/config/routing.html#balancerobject ，可以实现随机，这样的话最终效果和轮询是差不多的。

至于 vnext 和 users，我看了下代码，前者是轮询，后者是随机。

**Comment by rprx** [comment]
> 如果要使用CDN该如何配置才能实现负载均衡呢？

针对这个需求，而且指定轮询，我建议给 vnext 的数个 address 填 CDN 的不同 IP（同样适用于 VMess）。

**Comment by qiumzh** [comment]
```
{
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "domain",
                        "port": 443,
                        "users": [
                            {
                                "id": "6e01f4b4-22ba-cd12-6c16-3eb0b6cc3bee",
                                "level": 0,
                                "encryption": "none"
                            }
                        ]
                    },
                    {
                        "address": "domain",
                        "port": 443,
                        "users": [
                            {
                                "id": "fd3afd2f-474b-81b4-4727-169c90073589",
                                "level": 0,
                                "encryption": "none"
                            }
                        ]
                    },
                    {
                        "address": "domain",
                        "port": 443,
                        "users": [
                            {
                                "id": "5574f130-9446-4746-a426-d778369e9115",
                                "level": 0,
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "path": "/newjob"
                }
            },
            "tag": "proxy-vless-out"
        },
```
- 我把模板里的tlsSettings去掉了，然后`address`填写域名就可以了，并且可以用CDN

现在回到了旧的问题：
- VLESS over TCP with TLS + 回落（最简配置）是否也可以使用CDN？是不是一定要加websocket才能使用CDN呢？

**Comment by qiumzh** [comment]
> > 如果要使用CDN该如何配置才能实现负载均衡呢？
> 
> 针对这个需求，而且指定轮询，我建议给 vnext 的数个 address 填 CDN 的不同 IP（同样适用于 VMess）。

**Comment by rprx** [comment]
> 我把模板里的tlsSettings去掉了，然后address填写域名就可以了，并且可以用CDN

其实 address 填写不同的 IP 就可以了

> VLESS over TCP with TLS + 回落（最简配置）是否也可以使用CDN？是不是一定要加websocket才能使用CDN呢？

VLESS over TCP with TLS 通常不可以使用 CDN，WebSocket 通常可以。

**Comment by qiumzh** [comment]
> > 我把模板里的tlsSettings去掉了，然后address填写域名就可以了，并且可以用CDN
> 
> 其实 address 填写不同的 IP 就可以了。
> 
> > VLESS over TCP with TLS + 回落（最简配置）是否也可以使用CDN？是不是一定要加websocket才能使用CDN呢？
> 
> VLESS over TCP with TLS 通常不可以使用 CDN，WebSocket 通常可以。

非常感谢您的耐心解答，已经解开了我的疑问。
