### ISSUE TITLE
可否给个nginx的参考配置呀？

### ISSUE THREAD

**Issue by PangciPG** [v2fly/v2ray-examples#25]
对您的**VLESS-TCP-TLS-WS (recommended)**感兴趣，原来是ws + nginx and/or cdn； 是否可以顺便提供个简单的nginx参考呢？原来是在nginx进行tls验证转发到v2ray / 静态网页的；

**Comment by fangshixiong** [comment]
这是https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-TLS%20(maximal%20by%20rprx)
这个配置里，我用的nginx的配置

user www-data;
worker_processes auto;
pid /run/nginx.pid;
events {
 worker_connections 768;
}
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '$proxy_protocol_addr:$proxy_protocol_port';
    access_log  /var/log/nginx/access.log  main;
    error_log /var/log/nginx/error.log;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;
    gzip_disable "msie6";


    server {
        listen    [::]:80 default ipv6only=off;
        return    301 https://$http_host$request_uri;
    }


    server {
        listen    unix:/dev/shm/default.sock proxy_protocol;
        listen    unix:/dev/shm/h2c.sock http2 proxy_protocol;
        set_real_ip_from 127.0.0.1;
        location / {
            proxy_pass 填你想反代网站的网址;
        }
        error_page 404 /404.html;
            location = /40x.html {
        }
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
}

**Comment by xmapst** [comment]
静态网页还是得转到nginx/cdn才可以
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80  // nginx的80端口
                    },
                    {
                        "dest": 8443  // nginx的8443端口
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/path/to/fullchain.crt", // 换成你的证书，绝对路径
                            "keyFile": "/path/to/private.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                    "path": "/websocket" // 必须换成自定义的 PATH，需要和上面的一致
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```

**Comment by PangciPG** [comment]
感激！

**Comment by PangciPG** [comment]
> 静态网页还是得转到nginx/cdn才可以
> 
> ```
> {
>     "log": {
>         "loglevel": "warning"
>     },
>     "inbounds": [
>         {
>             "port": 443,
>             "protocol": "vless",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "", // 填写你的 UUID
>                         "level": 0,
>                         "email": "love@v2fly.org"
>                     }
>                 ],
>                 "decryption": "none",
>                 "fallbacks": [
>                     {
>                         "dest": 80  // nginx的80端口
>                     },
>                     {
>                         "dest": 8443  // nginx的8443端口
>                     },
>                     {
>                         "path": "/websocket", // 必须换成自定义的 PATH
>                         "dest": 1234,
>                         "xver": 1
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "tls",
>                 "tlsSettings": {
>                     "alpn": [
>                         "http/1.1"
>                     ],
>                     "certificates": [
>                         {
>                             "certificateFile": "/path/to/fullchain.crt", // 换成你的证书，绝对路径
>                             "keyFile": "/path/to/private.key" // 换成你的私钥，绝对路径
>                         }
>                     ]
>                 }
>             }
>         },
>         {
>             "port": 1234,
>             "listen": "127.0.0.1",
>             "protocol": "vless",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "", // 填写你的 UUID
>                         "level": 0,
>                         "email": "love@v2fly.org"
>                     }
>                 ],
>                 "decryption": "none"
>             },
>             "streamSettings": {
>                 "network": "ws",
>                 "security": "none",
>                 "wsSettings": {
>                     "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
>                     "path": "/websocket" // 必须换成自定义的 PATH，需要和上面的一致
>                 }
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "protocol": "freedom"
>         }
>     ]
> }
> ```

我可能没有表达清楚，我需要一个nginx的配置模板，配合这个v2ray配置的nginx的模板，"www.site.com.conf"

**Comment by mashiro-best** [comment]
见 [这里](https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS%20(maximal%20by%20rprx)/nginx.conf)

**Comment by PangciPG** [comment]
thx!
