### ISSUE TITLE
”TCP + TLS 分流器“不香么？VLESS over TCP with TLS + 回落 & 分流 to WebSocket 会更快？？

### ISSUE THREAD

**Issue by maryjeck** [v2fly/v2ray-examples#29]
”TCP + TLS 分流器“不香么？也可以用websocket+vless ，我也一直都是分流tcp+tls+vless和wss+tls+vless。
用的还不错。

VLESS over TCP with TLS + 回落 & 分流 to WebSocket 会更快？？

大神分析一下，

**Comment by rprx** [comment]
虽然你的描述看起来是在找茬，但看来我的确得抽时间完成“新型协议回落模式解析”，在此之前，建议自己先多想一想。

一个新的前置 VLESS 的理由：https://github.com/rprx/v2ray-vless/releases/tag/xtls
