### ISSUE TITLE
如何使用caddy2配合终极配置进行搭建。

### ISSUE THREAD

**Issue by DLGum** [v2fly/v2ray-examples#39]
自己尝试着修改折腾了整整一整天都没成功。最接近成功的是已经pin通了但就是用不了。没辙了。
[config.txt](https://github.com/v2fly/v2ray-examples/files/5331217/config.txt)

**Comment by maryjeck** [comment]
136行少了一个引号

**Comment by ixxmu** [comment]
调用caddy 证书请提前解决证书权限问题，另外 caddy证书无法被v2正确识别并调用，同样的证书位置,trojan没有任何问题

**Comment by maryjeck** [comment]
难怪今天试了一天，原来是caddy证书的问题

**Comment by maryjeck** [comment]
看教程是用certbot生成的，能否用acme生成
