### ISSUE TITLE
v2ray-examples/VLESS-TCP-XTLS-WHATEVER/config_client/vless_tcp_xtls.json有一点多余之处

### ISSUE THREAD

**Issue by luckypoem** [v2fly/v2ray-examples#43]
hi。

我看了这里https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_client/vless_tcp_xtls.json ，
vless_tcp_xtls.json文件有一点多余之处，那就是37-39行是多余的，完全可以删除。当然删除后，第36行末尾的逗号要去掉。

**Comment by GleenJi** [comment]
> 
> 
> hi。
> 
> 我看了这里https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_client/vless_tcp_xtls.json ，
> vless_tcp_xtls.json文件有一点多余之处，那就是37-39行是多余的，完全可以删除。当然删除后，第36行末尾的逗号要去掉。

多余是因为"address"是"example.com"，这个域名也默认应用在tls或xtls的servername和ws的hostname，如果"address"是IP地址或者CDN的IP，那就不多余，是必需要填写的

**Comment by rprx** [comment]
解释如上
