### ISSUE TITLE
In "VLESS-TCP-XTLS-WHATEVER/config_server.json", all vmess clients missing alterId item

### ISSUE THREAD

**Issue by celeron533** [v2fly/v2ray-examples#44]
https://github.com/v2fly/v2ray-examples/blob/cd71d227414b573e20b21065ce6d6af3214651ed/VLESS-TCP-XTLS-WHATEVER/config_server.json#L80-L91

https://github.com/v2fly/v2ray-examples/blob/cd71d227414b573e20b21065ce6d6af3214651ed/VLESS-TCP-XTLS-WHATEVER/config_server.json#L109-L120

**Comment by kslr** [comment]
vless 不需要 alterid

**Comment by celeron533** [comment]
> vless 不需要 alterid

sample中后两个端口都是vmess （只有端口`1234`是vless）

**Comment by celeron533** [comment]
另外`config_client`中两个vmess相关配置也有同样问题

不过都是小问题啦

**Comment by rprx** [comment]
alterId 为零（为空）代表 VMessAEAD，它也不需要 alterId，alterId 最终会被弃用。

**Comment by celeron533** [comment]
非常感谢解答@rprx
