### ISSUE TITLE
vless 是否支持多组id？

### ISSUE THREAD

**Issue by ixxmu** [v2fly/v2ray-examples#45]
如题vless是否支持多组id clients，测试的是开启多组id，就会无法连接，另，由vless直接回落到ws或者其他配置的时候，id是否需要保持为相同且唯一，望解答，谢谢

**Comment by rprx** [comment]
1. 支持，但为了防止使用者误以为成功开启了 XTLS，客户端不支持“选 XTLS 时不填 `flow`”，服务端无此限制。
2. 无任何限制，多个 inbounds 互不影响。
