### ISSUE TITLE
VLESS 服务器配置如何配置多端口多用户?

### ISSUE THREAD

**Issue by 80725015** [v2fly/v2ray-examples#49]
"inbounds": [
    {
    "port":65500,
      "listen": "127.0.0.1",
      "tag": "VLESS-in",
      "protocol": "VLESS",
      "settings": {
        "clients": [
          {
          "id":"115bd9e3-7b7f-4628-b4f6-23004ce7ada9",
            "alterId":0,
            "level":0
          }
        ],
            "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path":"/cs" 
        }
      }
    },
    {
      "port":65501,
      "listen": "127.0.0.1",
      "tag": "VLESS-in",
      "protocol": "VLESS",
      "settings": {
        "clients": [
          {
          "id":"d576b963-6a11-45f1-a89b-babe841f27f4",
            "alterId":0,
            "level":0
          }
        ],
            "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path":"/vless"
        }
      }
    }
但是最后只有65501能搜到被开启了？请问何解谢谢。

**Comment by rprx** [comment]
tag 不能重复。

（第二次遇到这种情况了，这是参考哪个教程写的吗？）

**Comment by 80725015** [comment]
我去，低级错误，对不起浪费大佬时间了。
是的，图省事，直接抄的。
