### ISSUE TITLE
Trojan 回落

### ISSUE THREAD

**Issue by azazjjyjjy** [v2fly/v2ray-examples#50]
感谢支持fallback功能。之前一直把trojan-gfw做外层，回落 v2ray使用达到共存。现在我想使用v2ray里的trojan协议达到类似效果：
尝试了一下外层是vless xtls，回落里面填写了 h2,ws,trojan.  最外层基本的vless xtls工作正常
如果把trojan的回落开启，path留空，用trojan尝试连接则服务端报错 not trojan request. //是不是trojan只能工作在最外层？
把trojan随便填个path禁用掉（trojan不支持path），则30086端口的vmess websocket可以正常工作；10086端口的h2还是不能工作，已经在alpn和xtls的alpn里都启用了h2。
我看到教程里写了 (非空则必须以 "/" 开头，不支持 h2c。) 也就是说回落是不支持h2的么？

如果要并存的话，是不是必须 trojan 外层，然后回落到 TLS的 vless和 vmess. 那么h2可以实现回落么？

"fallbacks": [
                    {
                        "alpn": "",
    			"path": "",
    			"dest": 80,
    			"xver": 0
                    },
                    {   "path": "/tro", // trojan 暂时禁用
                        "dest": 4433, 
                        "xver":1
                    },
                    {
                        "path": "/dodo", // vmess ws 兼容
                        "dest": 30086,
                        "xver": 1
                    },
                    {   "alpn":"h2",
                        "path": "/fat", 
                        "dest": 10086,
                        "xver": 1
                    }
                ]

**Comment by rprx** [comment]
错误认知和基于错误认知的提问比较多，只需两处纠错：

1. 不是 fallbacks 不支持 h2，只是 path 分流不支持 h2c
2. 请理解 xver 是什么，若不填 0，接收方应开启 acceptProxyProtocol，否则的确 `not trojan request`
