### ISSUE TITLE
v2ray 处理tls 性能问题

### ISSUE THREAD

**Issue by ixxmu** [v2fly/v2ray-examples#54]
同样的服务器，当v2ray处理TLS时，就会变得极其不稳定，但是换用caddy处理TLS就稳定许多，包括trojan，只要v2ray 处理TLS就会慢和不稳定，感觉现在限制vless扩大使用的就是TLS处理性能了

**Comment by smallprogram** [comment]
换XTLS

**Comment by ixxmu** [comment]
同样的配置，只要v2ray不处理tls，速度就很快，vless的场景使用必须需要v2处理TLS，所以现有的终极配置示例就是 从一堆慢里挑快，几乎没有多大意义

**Comment by smallprogram** [comment]
> 同样的配置，只要v2ray不处理tls，速度就很快，vless的场景使用必须需要v2处理TLS，所以现有的终极配置示例就是 从一堆慢里挑快，几乎没有多大意义

我是没有遇到你说的这种情况
