### ISSUE TITLE
修改服务器上CONFIG.JSON文件后出错

### ISSUE THREAD

**Issue by isaac574** [v2fly/v2ray-examples#55]
您好，搞了好久，不能自我解决，只好发问如下：
1）GOOGLE CLOULD上装了VLESS，用的是wulabing/V2Ray_ws-tls_bash_onekey的脚本。
2）今天按您的VLESS over TCP with XTLS + 回落 & 分流 to WHATEVER（终极配置）样本，修改V2RAY配置文件后出现：
root@ssrothk:~# sudo systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.
   Active: failed (Result: exit-code) since F
  Process: 3043 ExecStart=/usr/local/bin/v2ra
 Main PID: 3043 (code=exited, status=255/EXCE

Nov 20 14:04:53 ssrothk systemd[1]: v2ray.ser
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.ser
lines 1-8...skipping...
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-11-20 14:04:53 UTC; 7s ago
  Process: 3043 ExecStart=/usr/local/bin/v2ray -config /etc/v2ray/config.json (code=exited, status=255/EXCEPTION)
 Main PID: 3043 (code=exited, status=255/EXCEPTION)

Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Nov 20 14:04:53 ssrothk systemd[1]: Stopped V2Ray Service.
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Start request repeated too quickly.
Nov 20 14:04:53 ssrothk systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 20 14:04:53 ssrothk systemd[1]: Failed to start V2Ray Service.

3）我已将样本中所有注释删除。如下：
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "5aad5140-dfc4-46be-9dc7-dbbf11dd5e11", 
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 1310, 
                                                "xver": 1
                    },
                    {
                        "path": "/39b3b19b902aa/", 
                        "dest": 1234,
                        "xver": 1
                    },
                    {
                        "path": "/39b3b19b902aa/", 
                        "dest": 2345,
                        "xver": 1
                    },
                    {
                        "path": "/39b3b19b902aa/", 
                        "dest": 3456,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/root/.acme.sh/pearl.isaacserman.xyz_ecc/pearl.isaacserman.xyz.cer", 
                            "keyFile": "/root/.acme.sh/pearl.isaacserman.xyz_ecc/pearl.isaacserman.xyz.key" 
                        }
                    ]
                }
            }
        },
        {
            "port": 1310,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "", 
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 80 
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "5aad5140-dfc4-46be-9dc7-dbbf11dd5e11", 
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, 
                    "path": "/39b3b19b902aa/" 
                }
            }
        },
        {
            "port": 2345,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "5aad5140-dfc4-46be-9dc7-dbbf11dd5e11", 
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true,
                    "header": {
                        "type": "http",
                        "request": {
                            "path": [
                                "/39b3b19b902aa/" 
                            ]
                        }
                    }
                }
            }
        },
        {
            "port": 3456,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "5aad5140-dfc4-46be-9dc7-dbbf11dd5e11", 
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, 
                    "path": "/39b3b19b902aa/" 
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

还烦请赐教！

**Comment by kslr** [comment]
v2ray -c config.json 看一下错误
