### ISSUE TITLE
shadows 的 port 不能有 ""

### ISSUE THREAD

**Issue by kousyougi** [v2fly/v2ray-examples#59]
https://github.com/v2fly/v2ray-examples/blob/master/Shadowsocks-TCP/client.json

範例中，address 的IP 可以有 ""， 但port裡面不能有""。

            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "{{ host }}",
                        "port": "{{ port }}",
                        "method": "chacha20-ietf-poly1305",
                        "password": "{{ password}}"
                    }
                ]

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.
