### ISSUE TITLE
Please Fix Config File

### ISSUE THREAD

**Issue by ZhiShengYuan** [v2fly/v2ray-examples#70]
https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP/config_client.json
in this config file line 30,it's shouldn't be   "user": [ ,instead of it,it's "users": [

**Comment by kslr** [comment]
fixed https://github.com/v2fly/v2ray-examples/commit/e1e504eef326e539a58f5a3f6f16145e969ba94f
