### ISSUE TITLE
这样设置客户端不行

### ISSUE THREAD

**Issue by ghost** [v2fly/v2ray-examples#73]
我客户端是ubuntu desktop
/etc/vray/config.json:
照抄了 https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS%20(maximal%20by%20rprx)/config_client.json

      {
        "log": {
         "loglevel": "warning"
      },
          "inbounds": [
             {
              "port": 10800,
              "listen": "127.0.0.1",
              "protocol": "socks",
              "settings": {
                "udp": true
               }
          }
      ],
      "outbounds": [
          {
              "protocol": "vless",
              "settings": {
                  "vnext": [
                      {
                          "address": "example.com", // 换成你的域名或服务器 IP（发起请求时无需解析域名了）
                          "port": 443,
                          "users": [
                              {
                                  "id": "", // 填写你的 UUID
                                  "encryption": "none",
                                 "level": 0
                              }
                          ]
                      }
                  ]
              },
               "streamSettings": {
                    "network": "tcp",
                   "security": "tls",
                    "tlsSettings": {
                      "serverName": "example.com" // 换成你的域名
                  }
              }
             }
           ]
       }

上面我改了我该填的东西 然后

sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 10800:10800/tcp   -p 10800:10800/udp   v2fly/v2fly-core  v2ray -config=/etc/v2ray/config.json

然后在chrome上 在 swithcomage上设置了 127.0.0.1   10800 ，但是还是不行

我是ubuntu，服务端没问题的，服务端 是 v2fly vless tcp tls,Windows上用 v2rayng一点问题也没有

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-core/discussions
