### ISSUE TITLE
用 VMess-TCP 在 v2rayNG(安卓) 上无法连接

### ISSUE THREAD

**Issue by OlaWod** [v2fly/v2ray-examples#76]
我在 vultr 的服务器上把 /etc/v2ray/config.json 改成 VMess-TCP 的 config_server.json，然后 systemctl start v2ray，然后 systemctl status v2ray 显示正常运行；
在 v2rayNG (Google play 里下载的) 导入自定义配置 config_client.json，测试连接，有时候显示延时七八百毫秒，有时候显示 contet deadline exceeded，但是不管哪种情况浏览器都上不了网。
其他客户端没试过。
config_server.json 改了 id；config_client.json 改了 address 和 id；其他都没改。

**Comment by SeanWenkui** [comment]
我的v2ray一直工作的好好的（vmess+tcp），昨天开始突然上不了网了，折腾了一天，最后把服务器端和客户端的 alterId 删掉了，就可以上网了。2020-11-24日有人修改了example的配置，把alterid去掉了，没有说为什么。 https://github.com/v2fly/v2ray-examples/commit/7ec96b97dca86658f2b60fc34f9f805701cb02ac#diff-85082bd6cb1bd403db21964f61eef7e21c1e760b7c1023beda2b23d8cbb57899L26

**Comment by EpLiar** [comment]
https://www.v2fly.org/config/protocols/vmess.html#inboundconfigurationobject

> 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。

请使用 AEAD 认证方式，具体做法：`alterId: 0`
