### ISSUE TITLE
求【Routing Balancer】使用的具体示例

### ISSUE THREAD

**Issue by BI7PRK** [v2fly/v2ray-examples#77]
路由负载均衡的使用找不到具体的相关文档。搜索引擎里也找不到具体的应用方案。期待 examples 中给出一个具体的应用示例。谢谢！

**Comment by CHIZI-0618** [comment]
https://www.v2fly.org/config/routing.html#balancerobject
文档里很清楚

**Comment by BI7PRK** [comment]
THX @CHIZI-0618
