### ISSUE TITLE
Vless tcp fallback to vmess tcp 无法连接

### ISSUE THREAD

**Issue by jinwyp** [v2fly/v2ray-examples#79]
相关问题 https://github.com/XTLS/Xray-examples/issues/66

https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

按照上面这个教程 使用v2ray 核心

Vless tcp fallback to vmess tcp and vmess ws

vmess ws 是可以正常工作的， 但vmess 的 tcp 里面带path /vmesstcp 就无法连接

用脚本 bash <(curl -Lso- https://git.io/oneclick) 安装选13 就可以安装 vless fallback to vmess tcp 可以重现问题

印象中以前是可以的，不知道哪个版本后就不行了

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-examples/issues/66#issuecomment-1190259246

**Comment by jinwyp** [comment]
问题已解决 服务器端配置了 伪装类型 为 http , 而客户端的生成的配置漏了
